<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
	<AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
	<None Remove="Data\APT_BASE.csv" />
	<None Remove="Data\FIX_BASE.csv" />
	<None Remove="Data\na-countries.json" />
	<None Remove="Data\na-provinces.json" />
	<None Remove="Data\NAV_BASE.csv" />
	<None Remove="Data\tracon-boundaries.json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\APT_BASE.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Data\FIX_BASE.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Data\na-countries.json" />
    <EmbeddedResource Include="Data\na-provinces.json" />
    <EmbeddedResource Include="Data\NAV_BASE.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Data\tracon-boundaries.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.12" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.3.12" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Panels\MoveZoomPanelWindow.axaml.cs">
      <DependentUpon>MoveZoomPanelWindow.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Panels\SelectFeaFcaPanelWindow.axaml.cs">
      <DependentUpon>SelectFeaFcaPanelWindow.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
